config/routes.rb
Rails.application.routes.draw do
  get '/ask', to: 'questions#ask', as: :ask
  get '/answer', to: 'questions#answer', as: :awnser
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

# Question Controller
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @question = params[:question]
    @awnser = stupid_awnser(@question)
  end

  private

  def affirmative_phrases_awnser
    "I don't care, get dressed and go to work!"
  end

  def aquestion_phrases_awnser
    'Silly question, get dressed and go to work!.'
  end

  def good_awnser
    'Great!'
  end

  def stupid_awnser(question)
    return good_awnser if question == 'I am going to work'

    question.last == '?' ? aquestion_phrases_awnser : affirmative_phrases_awnser
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <h1>Stupid Coaching</h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="card">
  <p><%= @question %></p>
  <p>-You</p>
</div>

<div class="card active">
  <p><%= @awnser %></p>
  <p>-Your coach</p>
</div>
<%= link_to 'Ask a new question', ask_path %>

app/views/questions/ask.html.erb
<form action="<%= awnser_path %>">
  <div class="form-group">
    <label for="question">Ask your coach anything:</label>
    <div class="input-group">
      <input type="text" name="question"  id="question" class="form-control">
      <span class="input-group-btn">
        <input type="submit" class="btn btn-primary" value="Ask!">
      </span>
    </div>
  </div>
</form>